name: reconraptor-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - pandas=2.0.3
  - numpy=1.24.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.1
  - pytest=7.4.*
  - pytest-cov=4.1.*
